---
title: "Simple Bayesian Meta-Analysis"
author: "Pablo Emilio Verde"
date: "`r format(Sys.time(), '%b %d %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple Bayesian Meta-Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(jarbes)
```

# Introduction

In this vignette we describe the function **bmeta** for
simple Bayesian meta-analysis.


# Bayesian meta-analysis model


# Example: ppvipd

```{r}
## Not run: 
library(jarbes)

#Example: ppvipd
data("ppvipd")
bm1 = bmeta(ppvipd)

```


```{r}
summary(bm1)
```



```{r}
plot(bm1, x.lim = c(-3, 1), y.lim = c(0, 3))
```


```{r}

diagnostic(bm1, study.names = ppvipd$name, 
           post.p.value.cut = 0.1,
           lwd.forest = 1, shape.forest = 4)
```



# Example: stemcells


```{r}
data("stemcells")
stemcells$TE = stemcells$effect.size
stemcells$seTE = stemcells$se.effect
```


```{r}
bm2 = bmeta(stemcells)
```


```{r}
summary(bm2)
```


```{r}
plot(bm2, x.lim = c(-1, 7), y.lim = c(0, 1))
```


```{r}
diagnostic(bm2, study.names = stemcells$trial,
           post.p.value.cut = 0.05,
           lwd.forest = 0.5, shape.forest = 4)
```




